name: Upload SageMaker Code to S3

on:
  push:
    branches: [main]
    paths:
      - 'sagemaker/**'

  workflow_dispatch:  # allow manual trigger

jobs:
  upload:
    name: Upload training scripts to S3
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            us-east-1

      - name: Upload training script to S3
        run: |
          aws s3 cp sagemaker/training/train.py \
            s3://mlops-dev-mlflow-store/sagemaker/code/train.py

          echo "✅ Uploaded sagemaker/training/train.py"
          aws s3 ls s3://mlops-dev-mlflow-store/sagemaker/code/
