name: Upload SageMaker Code to S3

on:
  push:
    branches: [main]
    paths:
      - 'sagemaker/**'
  workflow_dispatch:

permissions:
  id-token: write   # required for OIDC
  contents: read

jobs:
  upload:
    name: Upload training scripts to S3
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC — no keys)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::482227257362:role/github-actions-mlops-role
          aws-region:     us-east-1

      - name: Upload training script to S3
        run: |
          aws s3 cp sagemaker/training/train.py \
            s3://mlops-dev-mlflow-store/sagemaker/code/train.py
          echo "✅ Uploaded sagemaker/training/train.py"
          aws s3 ls s3://mlops-dev-mlflow-store/sagemaker/code/
